default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: event_system_development
  password: <%= ENV["DATABASE_PASSWORD_LOCAL"] %>
  username: <%= ENV["DATABASE_USER_LOCAL"] %>
  host: <%= ENV["DATABASE_HOST_LOCAL"] %>

test:
  <<: *default
  database: event_system_test

production:
  <<: *default
  database: event_system_production
  username: event_system
  password: <%= ENV["EVENT_SYSTEM_DATABASE_PASSWORD"] %>
